export  const  MUTATIONS_SHOP_DETAIL = "MUTATIONS_SHOP_DETAIL";

export  const  MUTATIONS_ADD_SEARCH_HISTORY = "MUTATIONS_ADD_SEARCH_HISTORY";

export  const  MUTATIONS_REMOVE_SEARCH_HISTORY = "MUTATIONS_REMOVE_SEARCH_HISTORY";
export  const  MUTATIONS_REMOVE_ITEM_SEARCH_HISTORY = 'MUTATIONS_REMOVE_ITEM_SEARCH_HISTORY';
export const  MUTATIONS_SELECTED_SEARCH_ADDRESS = "MUTATIONS_SELECTED_SEARCH_ADDRESS";
